[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.0",
    "httpx>=0.28.1",
    "pydantic>=2.12.3",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
